const RECOMMENDED_CODES = [
  'AAA',
  'ARP',
  'S9R',
  'GOV',
  'XYD',
  'ADP',
  'GEE',
  'CVS',
  'FRD',
  'PAG',
  'MMM',
  'CAT',
  'ALL',
  'GAP',
  'COS',
  'VSA',
  'LOW',
  'HD1',
  'TXI',
  'TOY',
  'SW8',
  'FED',
  'UPS',
  'DTC',
  'ACC',
  'MCK',
  'MCO',
  'EYC',
  'PCW',
  'KPM',
  'GS1',
  'JPM',
  'MOS',
  'UBS',
  'BOE',
  'AMZ',
  'BOA',
  'BPA',
  'GGL',
  'GMC',
  'ATT',
  'APL',
  'DIS',
  'AMX',
];

const DEFAULT_PRESETS = [
  {
    id: 'quick10',
    name: 'Quick 10',
    icon: 'bolt',
    codes: ['AAA', 'GOV', 'S9R', 'ARP', 'GEE', 'DTC', 'ACC', 'MCO', 'GGL', 'CVS'],
    isDefault: true,
  },
  {
    id: 'recommended',
    name: 'Recommended',
    icon: 'star',
    codes: [],
    isDefault: true,
    dynamic: 'recommended',
  },
  {
    id: 'public-membership',
    name: 'Public / Membership',
    icon: 'person.2',
    codes: ['AAA', 'S9R', 'GOV', 'XYD', '295936', 'ARP', 'BAR', 'A9M'],
    isDefault: true,
  },
  {
    id: 'corporate-core',
    name: 'Corporate Core',
    icon: 'briefcase',
    codes: ['DTC', 'ACC', 'MCK', 'EYC', 'MCO', 'PCW', 'KPM', 'GGL', 'AMX', 'CVS', 'ATT', 'GMC'],
    isDefault: true,
  },
  {
    id: 'universities',
    name: 'Universities',
    icon: 'graduationcap',
    codes: ['ASU', 'DEV', 'DUK', 'FSU', 'HRV', '17885', 'HVD', 'MSU', 'MIT', '363006', 'NWU', 'OSU', 'PSU', 'STN', '349097', '60848', 'T72', 'UCB', 'UCLA', '364183', 'UC0', 'UFL', 'UGA', 'UM1', 'UM2', 'UNC', '4309', 'USC', 'UTX', '35902', 'UVA', 'UWI', 'YAL'],
    isDefault: true,
  },
  {
    id: 'marriott-internal',
    name: 'Marriott Internal',
    icon: 'person.badge.key',
    codes: ['MMP', 'MMF', 'MM4', 'EMP'],
    isDefault: true,
  },
  {
    id: 'promo-packages',
    name: 'Promo & Packages',
    icon: 'tag',
    codes: ['MEB', 'M11', 'M12', 'M96', 'XML', 'LTS', 'WKD', 'FR6', 'FXL', 'C9N', 'Z2H', 'CFY', 'V12', 'V88', 'ZJ5', 'ZJL', 'ZX0', 'ZEA', 'XES', 'D3Q', 'D34', 'D50', 'D18', 'D56', 'D58', 'D60', 'EAT', 'TFB', 'FML', 'NCL', 'F8L', 'ZH4', 'GOF', 'HON2', 'W14', 'PKF', 'PKG', 'PES', 'LVU', 'EMV', 'BOG', 'TZO', 'ADV', 'W8S', 'W9S', 'WCT', 'CUE', 'ENC', 'LRR', 'LPR', 'ZDY', 'W21', 'HOL', 'NPR', 'ARN', 'VIP', 'TRV', 'TVL', 'LLR', 'MRP', 'MR4', 'MR5', 'E0P', 'E0G', 'E0S'],
    isDefault: true,
  },
  {
    id: 'low-risk',
    name: 'Low Risk',
    icon: 'checkmark.shield',
    codes: ['ADP', 'GEE', 'CVS', 'FRD', 'PAG', 'MMM', 'CAT', 'ALL', 'GAP', 'COS', 'VSA', 'LOW', 'HD1', 'TXI', 'TOY', 'SW8', 'FED', 'UPS'],
    isDefault: true,
  },
  {
    id: 'high-value',
    name: 'High Value',
    icon: 'chart.line.uptrend.xyaxis',
    codes: ['GEE', 'DTC', 'MCK', 'ACC', 'MCO', 'EYC', 'PCW', 'KPM', 'GS1', 'JPM', 'MOS', 'UBS', 'BOE', 'AMZ', 'BOA', 'BPA', 'GGL', 'GMC', 'CVS', 'ATT', 'APL', 'DIS', 'AMX', 'ADP'],
    isDefault: true,
  },
  {
    id: 'best-usa',
    name: 'Best for USA',
    icon: 'flag',
    codes: ['DTC', 'MCK', 'ACC', 'EYC', 'GEE', 'MCO', 'AMX', 'GGL', 'GMC', 'CVS'],
    isDefault: true,
  },
  {
    id: 'best-europe',
    name: 'Best for Europe',
    icon: 'globe.europe.africa',
    codes: ['DTC', 'EYC', 'ACC', 'ATK', 'BPA', 'PCW', 'GGL', 'ADP', 'CIS', 'V12'],
    isDefault: true,
  },
  {
    id: 'best-asia',
    name: 'Best for Asia',
    icon: 'globe.central.south.asia',
    codes: ['GEE', 'APL', 'APP', 'APC', 'DIS', 'DTC', 'ATK', 'ADP', 'AMX', 'M96'],
    isDefault: true,
  },
  {
    id: 'best-australia',
    name: 'Best for Australia',
    icon: 'globe.asia.australia',
    codes: ['BHP', 'SCG', 'TWE', 'GEE', 'DTC', 'ACC', 'GGL', 'ATT', 'GMC', 'CVS'],
    isDefault: true,
  },
  {
    id: 'best-canada',
    name: 'Best for Canada',
    icon: 'map',
    codes: ['BCE', 'BMO', 'ROG', 'TDB', 'BOM', 'SCO', 'IRV', 'SLF', 'TLS', '57845'],
    isDefault: true,
  },
];

const CODE_DISPLAY = {
  BASELINE: 'STD',
};

module.exports = {
  CODE_DISPLAY,
  DEFAULT_PRESETS,
  RECOMMENDED_CODES,
};
